[project]
name = "dotfiles"
version = "0.1.0"
description = "Setup, config, automation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=13.1.0",
    "ansible-lint>=25.12.1",
    "jmespath>=1.0.1",
    "python-debian>=1.0.1",
]
